language: cpp
sudo: false
dist: xenial

addons:
  apt:
    packages:
    - libboost-dev
    - libboost-filesystem-dev
    - valgrind

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      env: COMPILER_C=gcc COMPILER_CXX=g++
    - os: linux
      compiler: clang
      env: COMPILER_C=clang COMPILER_CXX=clang++
    - os: linux
      compiler: gcc
      env: VALGRIND=ON
    - os: linux
      compiler: gcc
      env: USE_ICC=ON
    - os: linux
      compiler: gcc
      env: USE_PGI=ON
    - os: linux
      env: EMSCRIPTEN=ON
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      env: COMPILER_C=clang COMPILER_CXX=clang++
  allow_failures:
    - env: USE_ICC=ON
    - env: USE_PGI=ON

before_install:
  - cd $TRAVIS_BUILD_DIR
  - source ci/travis_setup.sh
  - $CC --version
  - $CXX --version

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - $CMAKE_CONFIGURE cmake .. $CMAKE_ARGS
  - make -j2
  - ctest -j2 --output-on-failure
