language: cpp
os: linux
dist: xenial

addons:
  apt:
    packages:
    - libboost-dev
    - libboost-filesystem-dev
    - valgrind

jobs:
  fast_finish: true
  include:
    - name: linux gcc
      os: linux
      compiler: gcc
      env: COMPILER_C=gcc COMPILER_CXX=g++
    - name: linux clang
      os: linux
      compiler: clang
      env: COMPILER_C=clang COMPILER_CXX=clang++
    - name: linux clang with warnings addressed
      os: linux
      compiler: clang
      env: COMPILER_C=clang COMPILER_CXX=clang++ DO_NOT_SUPPRESS_WARNINGS=ON
    - name: linux valgrind
      os: linux
      compiler: gcc
      env: VALGRIND=ON
    - name: linux icc
      os: linux
      compiler: gcc
      env: USE_ICC=ON
    - name: linux pgi
      os: linux
      compiler: gcc
      env: USE_PGI=ON
    - name: emscripten
      os: linux
      env: EMSCRIPTEN=ON
    - name: osx clang
      os: osx
      compiler: clang
      osx_image: xcode7.3
      env: COMPILER_C=clang COMPILER_CXX=clang++
  allow_failures:
    - env: USE_ICC=ON
    - env: USE_PGI=ON

before_install:
  - cd $TRAVIS_BUILD_DIR
  - source ci/travis_setup.sh
  - $CC --version
  - $CXX --version

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - $CMAKE_CONFIGURE cmake .. $CMAKE_ARGS
  - make -j2
  - ctest -j2 --output-on-failure
